version: "3"
services:
  postgres:
    container_name: emails-postgres
    image: postgres:latest
    ports:
      - "5434:5432"
    volumes:
      - pstgrs-data:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: emails-pgadmin
    image: dpage/pgadmin4
    ports:
      - "8082:80"
    volumes:
      - pg-data:/var/lib/pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

volumes:
  pstgrs-data:
  pg-data:

networks:
  postgres:
    driver: bridge
